server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: subscriptionupgrade
  profiles:
    active: ${ACTIVE_PROFILE:local}
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/timecard}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
